---
- name: Creating repository "{{ repo }}"
  vars:
    payload_repository:
      name: "{{ modifier }}{{ repo }}"
      description: ""
      private: "{{ private_repo }}"
      has_issues: true
      has_projects: true
      has_wiki: true
  uri:
    method: POST
    headers:
      Authorization: "Bearer {{ auth_source }}"
    status_code: 
      - 201
      - 422 # This code is returned when the repository already exists.
    url: "{{ endpoint }}"
    body_format: json
    body: "{{ payload_repository }}"
    return_content: yes
...