---
- name: Playbook for pulling repositories from a source and pusing to a destination
  hosts: localhost
  gather_facts: false
  vars:
    api_base_url_source: https://api.github.com

  pre_tasks:
    # This step loads all the variables needed for the plays.
  - name: Loading reposistories from file
    include_vars:
      file: repos.yml
      name: payload
  
  - name: parsing out the repositories from the payload
    set_fact:
      repos: "{{ payload.sampler}}"
      # repos: "{{ payload.repos }}"
  
  roles:
  - role: gitPullRepos
    vars:
      # entity: CapcoDevFx
      entity: codabilly
      # endpoint: gitCapco
      endpoint: gitCodabilly
    when: clean == False

  - role: repoCreator
    vars:
      # entity: bankunited
      # github_endpoint: /orgs/"{{ entity }}"/repos
      github_endpoint: /user/repos
      private_repo: true
      endpoint: "{{ api_base_url_source }}{{ github_endpoint }}"
      modifier: DB-
      auth_source: "{{ payload.github_api_token }}"
    when: clean == False
  
  - role: mirrorPushRepo
    vars:
      # entity: bankunited
      entity: C-BDraper
      endpoint: gitBacbdraper #comes from ssh config
      modifier: DB-
    when: clean == False

  - role: repoDelete
    vars:
      modifier: DB-
      # entity: bankunited
      entity: C-BDraper
      endpoint: "{{ api_base_url_source }}/repos/{{ entity }}" #same end poing for users or orgs
      auth_source: "{{ payload.github_api_token }}"
    when: clean == true
...